name: Build
on: 
  push: {}
  workflow_dispatch: {}
  schedule:
    - cron: '30 3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Docker image tag version
        id: image-name
        run: |
          case "$GITHUB_REF" in
            refs/heads/master)
              TAG=latest;;
            *)
              echo "Branch not recognized" >&2
              exit;;
          esac

          : ${TAG:=latest}
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=name::yangzhaofengsteven/danted:$TAG"
      - name: Build Docker image
        run: |
          IMAGE="${{ steps.image-name.outputs.name }}"
          docker pull "$IMAGE"
          docker build --cache-from "$IMAGE" -t build-image .
      - name: Push to Docker Hub
        if: "github.repository == 'yangzhaofeng/docker-danted'"
        run: |
          IMAGE="${{ steps.image-name.outputs.name }}"
          docker tag build-image "$IMAGE"
          docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"
          docker push "$IMAGE"

